import { Icon } from '@iconify/react';

const TripResult = ({ result, onReset }) => {
  // Normalize result to a string
  const textResult =
    typeof result === 'string'
      ? result
      : Array.isArray(result?.parts)
      ? result.parts.map((p) => p.text).join('\n')
      : '';

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      {/* Header Card */}
      <div className="bg-primary-600 shadow-lg p-8 text-white rounded-lg">
        <div className="flex flex-col md:flex-row justify-between items-center gap-4">
          <div className="flex items-center space-x-4">
            <div className="bg-white p-4 shadow-md rounded-full">
              <Icon icon="mdi:map-check" className="text-5xl text-primary-600" />
            </div>
            <div>
              <h2 className="text-3xl font-medium mb-1">Your Trip Itinerary</h2>
              <p className="text-primary-100 flex items-center space-x-2">
                <Icon icon="mdi:robot" className="text-xl" />
                <span>Generated by AI</span>
              </p>
            </div>
          </div>
          <button
            onClick={onReset}
            className="bg-white text-primary-600 hover:bg-gray-100 font-medium py-3 px-6 transition-colors flex items-center space-x-2 shadow-md rounded"
          >
            <Icon icon="mdi:refresh" className="text-xl" />
            <span>Plan Another Trip</span>
          </button>
        </div>
      </div>

      {/* Content Card */}
      <div className="bg-white shadow-lg p-8 rounded-lg">
        <div className="space-y-4 text-gray-700 leading-relaxed">
          {textResult.split('\n').map((line, index) => {
            // Section headers (##)
            if (line.startsWith('##')) {
              return (
                <div
                  key={index}
                  className="flex items-center space-x-3 mt-8 mb-4 pb-3 border-b-2 border-primary-600"
                >
                  <Icon icon="mdi:map-marker" className="text-3xl text-primary-600 flex-shrink-0" />
                  <h3 className="text-2xl font-medium text-gray-900 m-0">
                    {line.replace('##', '').trim()}
                  </h3>
                </div>
              );
            }

            // Bold text / Day headers
            if (line.startsWith('**') || line.includes('**')) {
              return (
                <div
                  key={index}
                  className="flex items-center space-x-2 bg-primary-50 p-4 mt-6 mb-3 border-l-4 border-primary-600 shadow-sm rounded"
                >
                  <Icon icon="mdi:calendar" className="text-2xl text-primary-600 flex-shrink-0" />
                  <p className="font-medium text-gray-900 text-lg m-0">{line.replace(/\*\*/g, '')}</p>
                </div>
              );
            }

            // List items (- or *)
            if (line.trim().startsWith('-') || line.trim().startsWith('*')) {
              return (
                <div
                  key={index}
                  className="flex items-start space-x-3 ml-4 mb-3 hover:bg-gray-50 p-3 transition-colors rounded"
                >
                  <Icon icon="mdi:check-circle" className="text-xl text-primary-600 flex-shrink-0 mt-0.5" />
                  <li className="list-none m-0 text-gray-700">{line.replace(/^[-*]\s*/, '')}</li>
                </div>
              );
            }

            // Regular paragraph
            if (line.trim()) {
              return (
                <p key={index} className="mb-3 text-gray-700 leading-relaxed">
                  {line}
                </p>
              );
            }

            return <div key={index} className="h-2" />;
          })}
        </div>
      </div>

      {/* Action Cards */}
      <div className="grid md:grid-cols-2 gap-4">
        <div className="bg-white p-6 border-2 border-primary-600 shadow-md rounded-lg">
          <div className="flex items-start space-x-3">
            <Icon icon="mdi:information" className="text-3xl text-primary-600 flex-shrink-0" />
            <div>
              <h4 className="font-medium text-gray-900 mb-2">Important Note</h4>
              <p className="text-sm text-gray-700">
                This itinerary is AI-generated. Please verify details, check opening hours, and make reservations in
                advance.
              </p>
            </div>
          </div>
        </div>

        <div className="bg-white p-6 border-2 border-gray-300 shadow-md rounded-lg">
          <div className="flex items-start space-x-3">
            <Icon icon="mdi:bookmark" className="text-3xl text-gray-600 flex-shrink-0" />
            <div>
              <h4 className="font-medium text-gray-900 mb-2">Save Your Plan</h4>
              <p className="text-sm text-gray-700">
                Copy this itinerary or take screenshots to keep it handy during your trip.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TripResult;
